version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    working_directory: ~/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ./
      - add_ssh_keys
      - deploy:
          name: "Publish Page"
          command: ./.circleci/deploy-gh-pages.sh
