# This is the main configuration file for Netlify CMS.
# Netlify CMS is used as the admin panel for cState.
#
# While some settings here can be kept as is, you may
# want to change some for a more customized solution.
#
# You can look at what each option does and how to
# toggle between them on the Netlify CMS repo docs:
#
# https://github.com/netlify/netlify-cms/blob/master/docs/quick-start.md

backend:
  name: github
  repo: BundesIT/statuspage
  site_domain: relaxed-lewin-ca531e.netlify.com

media_folder: "static/img"
public_folder: "/img"
display_url: /

# Do not change this!
collections:
  - name: "issues"
    label: "Störungen"
    label_singular: "Störung"
    description: "Willkommen im IT Störungs Pannel. Hier kannst du neue Störung einstellen und bestehende bearbeiten"
    folder: "content/issues"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Als Störung markieren", name: "section", widget: "hidden", default: "issue"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Start: Zeit & Datum", name: "date", widget: "datetime"}
      - {label: "Als behoben markieren", name: "resolved", widget: "boolean", required: false}
      - {label: "Ende: Zeit & Datum", name: "resolvedWhen", widget: "datetime", required: false}
      - label: "Betroffene Systeme (exakte namen verwenden, mit Komma trennen)"
        name: "affected"
        widget: "list"
        required: false
      - label: "Schwere"
        name: "severity"
        widget: "select"
        options:
          - { label: "Hoch (Down)", value: "down" }
          - { label: "Mittel (Ausfälle, geht aber noch)", value: "disrupted" }
          - { label: "Niedrig (Ankündigung)", value: "notice" }
      - label: "Markdown Text (Reihenfolge der Ereignisse, Beschreibung, post-mortem)"
        name: "body"
        widget: "markdown"
        default: "*Analyse* - Wir analysieren zur Zeit Probleme in unserer Infrastruktur. Sobald wir genaueres wissen, werden wir euch hier informieren."